### ISSUE TITLE
Does the redmi note 10 pro work?

### ISSUE THREAD

**Issue by Pop7362** [woa-miatoll/Port-Windows-11-Redmi-Note-9-Pro#1]
### Question

Does the redmi note 10 pro work?

### Agreement

- [ ] I am asking a sensible question.
- [ ] I am not trying to waste time.
- [x] There is no issue already describing my problem.

**Comment by N1kroks** [comment]
No, 732g does not have wp equivalent

**Comment by 0944-tw** [comment]
> No, 732g does not have wp equivalent

but hmmm 732g and 730 and 730g are same codename...
https://wiki.postmarketos.org/wiki/Qualcomm_Snapdragon_730/730G/732G_(SM7150)

**Comment by N1kroks** [comment]
> > No, 732g does not have wp equivalent
> 
> but hmmm 732g and 730 and 730g are same codename... https://wiki.postmarketos.org/wiki/Qualcomm_Snapdragon_730/730G/732G_(SM7150)
> 
> also looks like i found another 732G device running WoA https://github.com/SebastianZSXS/Poco-X3-NFC-WindowsARM/blob/main/language/english.md

You can install windows, but nothing will work in it
