### ISSUE TITLE
Can I run windows 10 also , do drivers support windows 10 ?

### ISSUE THREAD

**Issue by atharva288** [woa-miatoll/Port-Windows-11-Redmi-Note-9-Pro#3]
### Question

I installed windows 11 , will it work on 10 ?

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by N1kroks** [comment]
You can run windows 10 but no support will be provided if something does not work
