### ISSUE TITLE
[QUESTION] - Can it run on 4/64?

### ISSUE THREAD

**Issue by misha99fr** [woa-miatoll/Port-Windows-11-Redmi-Note-9-Pro#4]
### Question

I have a 4/64 redmi note 9s, and i wondering if i can run on 4/64?

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by atharva288** [comment]
I
Yes it can run on 4 gb
