### ISSUE TITLE
[BUG] - can not run it on  redmi note 9 pro (gauguin)

### ISSUE THREAD

**Issue by moshuying** [woa-miatoll/Port-Windows-11-Redmi-Note-9-Pro#5]
### Description

i was try install recovery(ofox) to my device, it will be cycle reboot to fastboot, can not run it

### Reproduction steps

```bash
bug
```

### Agreement

- [X] I am using the latest Drivers.
- [X] I am running Windows 11 On The Phone.
- [X] There is no issue already describing my problem.

**Comment by N1kroks** [comment]
Gauguin is redmi note 9 pro 5g which is not supported
